apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
  namespace: tekton-pipelines
  labels:
    app: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
        - name: request-forwarder
          image: cerberus2k/request-forwarder:latest
          ports:
            - containerPort: 8080
